# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title : '만월님의 포트폴리오 사이트'
author : 'fullmoon'
image : ''
keywords : ''
description: '설명'


email: your-email@domain.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://a-fullmoon.github.io/" # the base hostname & protocol for your site